/**
 * TTN gateway coverage layer.
 *
 * Renders two static MultiPolygon snapshots pre-computed offline by
 * `npm run gateways:refresh`:
 *
 *   1. `public/ttnmapper-coverage.json` — union of 150 km buffers around
 *      every gateway. Filled + outlined.
 *   2. `public/ttnmapper-coverage-outer.json` — union of 250 km buffers.
 *      Outline only (dashed).
 *
 * The two outlines together read like concentric isolines: solid inner
 * line = "definite reception" envelope, dashed outer line = "best-case
 * line-of-sight" envelope.
 *
 * Per-gateway points are no longer rendered — in dense regions the
 * fireflies + 14k overlapping rings drowned the signal we actually care
 * about, which is "where does coverage stop." The static gateways JSON
 * is still generated by the refresh script as the basis for the union
 * computation; it's just not displayed.
 *
 * Usage: drop `<GatewayLayer />` inside a react-map-gl `<Map>`.
 */
'use client';

import { useEffect, useMemo, useState } from 'react';
import { Layer, Source } from 'react-map-gl/mapbox';
import type { Feature, MultiPolygon, Polygon } from 'geojson';

type CoverageGeometry = MultiPolygon | Polygon;

/* Module-level memos so multiple <GatewayLayer /> instances on the same
 * page share one fetch of each file. */
let cachedCoverage: CoverageGeometry | null = null;
let inFlightCoverage: Promise<CoverageGeometry | null> | null = null;

let cachedCoverageOuter: CoverageGeometry | null = null;
let inFlightCoverageOuter: Promise<CoverageGeometry | null> | null = null;

async function loadCoverage(): Promise<CoverageGeometry | null> {
    if (cachedCoverage) return cachedCoverage;
    if (inFlightCoverage) return inFlightCoverage;
    inFlightCoverage = (async () => {
        try {
            const r = await fetch('/ttnmapper-coverage.json');
            if (!r.ok) return null;
            const body = (await r.json()) as { coverage: CoverageGeometry };
            cachedCoverage = body.coverage ?? null;
            return cachedCoverage;
        } catch {
            return null;
        } finally {
            inFlightCoverage = null;
        }
    })();
    return inFlightCoverage;
}

async function loadCoverageOuter(): Promise<CoverageGeometry | null> {
    if (cachedCoverageOuter) return cachedCoverageOuter;
    if (inFlightCoverageOuter) return inFlightCoverageOuter;
    inFlightCoverageOuter = (async () => {
        try {
            const r = await fetch('/ttnmapper-coverage-outer.json');
            if (!r.ok) return null;
            const body = (await r.json()) as { coverage: CoverageGeometry };
            cachedCoverageOuter = body.coverage ?? null;
            return cachedCoverageOuter;
        } catch {
            return null;
        } finally {
            inFlightCoverageOuter = null;
        }
    })();
    return inFlightCoverageOuter;
}

export interface GatewayLayerProps {
    /** Stops rendering when false (e.g. tied to a user toggle). */
    visible?: boolean;
    /** Basemap — coverage washes are brightened on the dark map, where the
     *  quiet slate tones used on the light map all but vanish. */
    colorScheme?: 'light' | 'dark';
}

/* Coverage wash tones per basemap. Dark mode uses a brighter teal at higher
 * opacity so the "where reception lives" field reads against the dark map. */
const COVERAGE_STYLE = {
    light: {
        fill: '#5a5c62',
        fillOpacity: 0.05,
        innerLine: 'rgba(90, 92, 98, 0.26)',
        outerLine: 'rgba(90, 92, 98, 0.30)',
    },
    dark: {
        fill: '#4a8c96',
        fillOpacity: 0.07,
        innerLine: 'rgba(110, 180, 190, 0.34)',
        outerLine: 'rgba(110, 180, 190, 0.24)',
    },
} as const;

export default function GatewayLayer({ visible = true, colorScheme = 'light' }: GatewayLayerProps) {
    const cov = COVERAGE_STYLE[colorScheme];
    const [coverage, setCoverage] = useState<CoverageGeometry | null>(null);
    const [coverageOuter, setCoverageOuter] = useState<CoverageGeometry | null>(null);

    useEffect(() => {
        /* No `firedRef` gate here: React 19's Strict-Mode double-mount in
         * dev would set `fired` on the first mount, run its cleanup
         * (setting `cancelled = true`), and then the second mount would
         * see `fired === true` and skip — but the first mount's promise
         * would never resolve back into state because it was cancelled.
         * Result: permanent null state. We rely instead on the module-
         * level memos to make the fetches idempotent. */
        let cancelled = false;
        loadCoverage().then(cov => {
            if (!cancelled && cov) setCoverage(cov);
        });
        loadCoverageOuter().then(cov => {
            if (!cancelled && cov) setCoverageOuter(cov);
        });
        return () => { cancelled = true; };
    }, []);

    const coverageGeoJSON = useMemo<Feature<CoverageGeometry> | null>(() => {
        if (!coverage) return null;
        return {
            type: 'Feature',
            geometry: coverage,
            properties: {},
        };
    }, [coverage]);

    const coverageOuterGeoJSON = useMemo<Feature<CoverageGeometry> | null>(() => {
        if (!coverageOuter) return null;
        return {
            type: 'Feature',
            geometry: coverageOuter,
            properties: {},
        };
    }, [coverageOuter]);

    if (!visible) return null;

    return (
        <>
            {/* Outer (250 km) coverage union — outline only. Renders
              * first so the inner 150 km outline draws on top. The two
              * lines together read like concentric isolines: definite
              * reception (inner) vs. best-case line-of-sight (outer). */}
            {coverageOuterGeoJSON && (
                <Source id="tm-coverage-outer" type="geojson" data={coverageOuterGeoJSON}>
                    <Layer
                        id="tm-coverage-outer-outline"
                        type="line"
                        paint={{
                            'line-color': cov.outerLine,
                            'line-width': 0.75,
                            'line-dasharray': [2, 2.5],
                        }}
                    />
                </Source>
            )}

            {/* Inner (150 km) coverage union — faint slate fill + hairline. Reads
              * as a quiet "where reception lives" wash, not a glowing layer. */}
            {coverageGeoJSON && (
                <Source id="tm-coverage" type="geojson" data={coverageGeoJSON}>
                    <Layer
                        id="tm-coverage-fill"
                        type="fill"
                        paint={{
                            'fill-color': cov.fill,
                            'fill-opacity': cov.fillOpacity,
                        }}
                    />
                    <Layer
                        id="tm-coverage-outline"
                        type="line"
                        paint={{
                            'line-color': cov.innerLine,
                            'line-width': 0.6,
                        }}
                    />
                </Source>
            )}
        </>
    );
}
