#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "lorawan_crypto.h"

static void from_hex(const char* hex, uint8_t* out, size_t length) {
    for (size_t i = 0; i < length; ++i) {
        unsigned value = 0;
        assert(sscanf(hex + i * 2, "%2x", &value) == 1);
        out[i] = (uint8_t)value;
    }
}

static void expect_hex(const uint8_t* actual, size_t length,
                       const char* expected_hex) {
    uint8_t expected[64] = {};
    assert(length <= sizeof(expected));
    from_hex(expected_hex, expected, length);
    assert(memcmp(actual, expected, length) == 0);
}

int main(void) {
    /* Generated by analysis/diagnostics/generate_lorawan_crypto_vectors.mjs
     * using Node/OpenSSL AES; its CMAC generator is independently guarded by
     * RFC 4493 and the MIC was also cross-checked with `openssl mac CMAC`. */
    uint8_t app_key[16], nwk_key[16];
    from_hex("000102030405060708090a0b0c0d0e0f", app_key, 16);
    from_hex("2b7e151628aed2a6abf7158809cf4f3c", nwk_key, 16);
    const uint32_t dev_addr = 0x26011BDAu;
    const uint32_t frame_counter = 0x00010203u;

    uint8_t payload[33];
    from_hex(
        "000102030405060708090a0b0c0d0e0f"
        "101112131415161718191a1b1c1d1e1f20",
        payload, sizeof(payload));
    assert(lorawan_crypto_payload(app_key, dev_addr, frame_counter, 0,
                                  payload, sizeof(payload)));
    expect_hex(
        payload, sizeof(payload),
        "e8bd6affeac3eec67d46a9677343b55a"
        "5510b9fc10469f7f4a18f0f8c85e53026b");
    /* CTR encrypt/decrypt is symmetric and must handle a partial final block. */
    assert(lorawan_crypto_payload(app_key, dev_addr, frame_counter, 0,
                                  payload, sizeof(payload)));
    expect_hex(
        payload, sizeof(payload),
        "000102030405060708090a0b0c0d0e0f"
        "101112131415161718191a1b1c1d1e1f20");
    assert(lorawan_crypto_payload(app_key, dev_addr, frame_counter, 1,
                                  payload, sizeof(payload)));
    expect_hex(
        payload, sizeof(payload),
        "5cad3bdf683bb9f950df4e7bf1a66927"
        "70282f4948f30d20d2985fd5e6ddb6320d");
    assert(lorawan_crypto_payload(app_key, dev_addr, frame_counter, 1,
                                  payload, sizeof(payload)));

    uint8_t message[18];
    from_hex("40da1b01260003010a010203040506070809",
             message, sizeof(message));
    uint8_t mic[4];
    assert(lorawan_crypto_mic(nwk_key, dev_addr, frame_counter, 0,
                              message, sizeof(message), mic));
    expect_hex(mic, sizeof(mic), "76da0ffe");
    assert(lorawan_crypto_mic(nwk_key, dev_addr, frame_counter, 1,
                              message, sizeof(message), mic));
    expect_hex(mic, sizeof(mic), "088dc404");

    const uint8_t join_nonce[3] = {1, 2, 3};
    const uint8_t net_id[3] = {4, 5, 6};
    uint8_t session_key[16];
    assert(lorawan_crypto_session_key(app_key, 1, join_nonce, net_id,
                                      0x0708, session_key));
    expect_hex(session_key, 16, "cd568c6dd7c21f70b062e1c541f99dea");
    assert(lorawan_crypto_session_key(app_key, 2, join_nonce, net_id,
                                      0x0708, session_key));
    expect_hex(session_key, 16, "72e6eacbcd650de2393b5ce1456b4e28");

    uint8_t join[32];
    from_hex(
        "00112233445566778899aabbccddeeff"
        "ffeeddccbbaa99887766554433221100",
        join, sizeof(join));
    assert(lorawan_crypto_join_accept(app_key, join, sizeof(join), join));
    expect_hex(
        join, sizeof(join),
        "69c4e0d86a7b0430d8cdb78070b4c55a"
        "1b872378795f4ffd772855fc87ca964d");

    assert(lorawan_crypto_payload(app_key, 0, 0, 0, nullptr, 0));
    assert(!lorawan_crypto_payload(app_key, 0, 0, 2, payload, 1));
    assert(!lorawan_crypto_payload(nullptr, 0, 0, 0, payload, 1));
    assert(!lorawan_crypto_mic(nwk_key, 0, 0, 2, message, 1, mic));
    assert(!lorawan_crypto_mic(nwk_key, 0, 0, 0, nullptr, 1, mic));
    assert(!lorawan_crypto_join_accept(app_key, join, 17, join));
    assert(!lorawan_crypto_join_accept(app_key, join, 0, join));
    assert(!lorawan_crypto_session_key(app_key, 3, join_nonce, net_id,
                                       0, session_key));

    puts("LoRaWAN crypto: payload/MIC/join/session interoperability vectors passed");
    return 0;
}
