M48
; DRILL file {KiCad 8.0.3} date 2026-02-13T10:03:00-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-13T10:03:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X2.2086Y-2.1907
T2
X2.2742Y-3.2948
X2.4742Y-3.3348
X2.4742Y-3.2548
M30
