export const colors=['#d34a53','#df812e','#b59a21','#42966b','#328cb3','#6161bb','#a85599'];
const ns='http://www.w3.org/2000/svg';
const el=(tag,attrs={},text)=>{const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;};
const fmt=(n,p=1)=>Number(n).toLocaleString('en-US',{maximumFractionDigits:p});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let dataset;const data=()=>dataset??=fetch('/assets/payload-dev-log/charts.json').then(r=>{if(!r.ok)throw Error();return r.json();});
function shell(host,title){host.replaceChildren();const h=document.createElement('div');h.className='chart-heading';h.textContent=title;const stage=document.createElement('div');stage.className='chart-stage';const legend=document.createElement('div');legend.className='chart-legend';const read=document.createElement('output');read.className='chart-readout';host.append(h,legend,stage,read);return{h,stage,legend,read};}
function control(host,label,min,max,value,step=1){const l=document.createElement('label');l.className='chart-control';const txt=document.createElement('span');txt.textContent=label;const o=document.createElement('output');o.textContent=value;const input=document.createElement('input');input.type='range';Object.assign(input,{min,max,value,step});input.setAttribute('aria-label',label);l.append(txt,o,input);host.append(l);input.addEventListener('input',()=>o.textContent=input.value);return input;}
function swatch(name,color,container){const s=document.createElement('span');s.className='chart-key';const i=document.createElement('i');i.style.background=colors[color];s.append(i,document.createTextNode(name));container.append(s);}
function xyChart(host,d,signal){const ui=shell(host,d.title);const svg=el('svg',{role:'img','aria-label':d.title,tabindex:0});ui.stage.append(svg);let size,scales,points=[],focusX=null;const hidden=new Set();
 d.series.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-pressed','true');b.setAttribute('aria-label',`Show ${s.name}`);swatch(s.name,s.color,b);if(d.colorByX){const key=b.querySelector('i');key.style.background='#535861';key.style.opacity=i===0?'.48':'1';key.style.height='10px';}ui.legend.append(b);b.onclick=()=>{if(hidden.has(i))hidden.delete(i);else if(hidden.size<d.series.length-1)hidden.add(i);b.setAttribute('aria-pressed',String(!hidden.has(i)));draw();};});
 if(d.median!==undefined)swatch(`Median ${fmt(d.median)}°`,0,ui.legend);
 function draw(){const w=host.clientWidth-32,h=w<450?290:340,L=w<450?44:58,R=15,T=27,B=49;size={w,h,L,R,T,B};svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('width',w);svg.setAttribute('height',h);svg.replaceChildren();points=[];
 const ss=d.series.filter((_,i)=>!hidden.has(i)),allX=ss.flatMap(s=>s.x),allY=ss.flatMap(s=>s.y);let xmin=Math.min(...allX),xmax=Math.max(...allX),ymin=Math.min(0,...allY),ymax=Math.max(...allY);if(d.domainY)[ymin,ymax]=d.domainY;else{const pad=(ymax-ymin||1)*.08;ymax+=pad;if(ymin<0)ymin-=pad;}if(d.kind==='bar'){xmin-=d.binWidth||.5;xmax+=d.binWidth||.5;}if(xmin===xmax)xmax++;const sx=x=>L+(x-xmin)/(xmax-xmin)*(w-L-R),sy=y=>T+(1-(y-ymin)/(ymax-ymin))*(h-T-B);scales={sx,sy,xmin,xmax,ymin,ymax};
 svg.append(el('text',{x:L,y:14,class:'axis-label'},d.ylabel));const ticks=4;for(let k=0;k<=ticks;k++){const v=ymin+(ymax-ymin)*k/ticks,y=sy(v);svg.append(el('line',{x1:L,x2:w-R,y1:y,y2:y,class:'grid-line'}),el('text',{x:L-9,y:y+4,'text-anchor':'end',class:'tick'},fmt(v,Math.abs(v)<10?1:0)));}
 const xt=d.categories?d.categories.map((_,i)=>i):d.kind==='bar'&&!d.binWidth?d.series[0].x:Array.from({length:5},(_,k)=>xmin+(xmax-xmin)*k/4);xt.forEach(v=>svg.append(el('text',{x:sx(v),y:h-B+22,'text-anchor':'middle',class:'tick'},d.categories?.[v]??fmt(v,Math.abs(v)<10?1:0))));svg.append(el('text',{x:L+(w-L-R)/2,y:h-5,'text-anchor':'middle',class:'axis-label'},d.xlabel));
 const clipId=`clip-${host.dataset.chart}`;const defs=el('defs'),cp=el('clipPath',{id:clipId});cp.append(el('rect',{x:L,y:T,width:w-L-R,height:h-T-B}));defs.append(cp);svg.append(defs);const marks=el('g',{'clip-path':`url(#${clipId})`});svg.append(marks);
 ss.forEach((s,i)=>{const col=colors[s.color],coords=s.x.map((x,k)=>[sx(x),sy(s.y[k])]);if(d.kind==='scatter')coords.forEach(([x,y],k)=>{marks.append(el('circle',{cx:x,cy:y,r:s.name.includes('Cached')?2:3,fill:col,opacity:s.name.includes('Cached')?.22:.85}));points.push({x,y,xv:s.x[k],yv:s.y[k],name:s.name,color:col});});else if(d.kind==='bar'){const width=d.binWidth?(sx(d.binWidth)-sx(0))*.82:(w-L-R)/(s.x.length+1)*.68;coords.forEach(([x,y],k)=>{const bw=width/ss.length,x0=x-width/2+i*bw;marks.append(el('rect',{x:x0,y:Math.min(sy(0),y),width:bw*.88,height:Math.abs(sy(0)-y),rx:2,fill:d.colorByX?colors[k%7]:col,opacity:i===0&&d.colorByX?.48:1}));});}else{marks.append(el('path',{d:coords.map(([x,y],k)=>`${k?'L':'M'}${x},${y}`).join(' '),fill:'none',stroke:col,'stroke-width':2.2,'stroke-linejoin':'round'}));if(d.markers)coords.forEach(([x,y])=>marks.append(el('circle',{cx:x,cy:y,r:3,fill:col})));}});
 if(d.median!==undefined)marks.append(el('line',{x1:sx(d.median),x2:sx(d.median),y1:T,y2:h-B,stroke:colors[0],'stroke-dasharray':'4 4'}));
 inspect(focusX??(xmin+xmax)/2);
 }
 function inspect(xv,py){if(!scales)return;const{sx,sy,xmin,xmax}=scales;focusX=clamp(xv,xmin,xmax);svg.querySelector('.chart-cursor')?.remove();const cursor=el('g',{class:'chart-cursor','pointer-events':'none'});svg.append(cursor);const ss=d.series.filter((_,i)=>!hidden.has(i));if(d.kind==='bar')focusX=ss[0].x.reduce((a,b)=>Math.abs(a-focusX)<Math.abs(b-focusX)?a:b);let values=[];if(d.kind==='scatter'){const p=points.reduce((best,p)=>Math.hypot(p.x-sx(focusX),p.y-(py??size.h/2))<Math.hypot(best.x-sx(focusX),best.y-(py??size.h/2))?p:best,points[0]);if(p){cursor.append(el('circle',{cx:p.x,cy:p.y,r:6,fill:'none',stroke:p.color,'stroke-width':2}));values=[`${p.name}: ${fmt(p.xv)} km, ${fmt(p.yv)}°`];}}else{cursor.append(el('line',{x1:sx(focusX),x2:sx(focusX),y1:size.T,y2:size.h-size.B,stroke:'#46444166','stroke-dasharray':'3 4'}));ss.forEach(s=>{const k=s.x.reduce((best,v,i)=>Math.abs(v-focusX)<Math.abs(s.x[best]-focusX)?i:best,0);const y=s.y[k];if(y>=scales.ymin&&y<=scales.ymax)cursor.append(el('circle',{cx:sx(s.x[k]),cy:sy(y),r:4,fill:colors[d.colorByX?k%7:s.color],stroke:'#f6f4ef','stroke-width':2}));values.push(`${s.name}: ${fmt(y,2)}`);});const base=ss[0];const k=base.x.reduce((b,v,i)=>Math.abs(v-focusX)<Math.abs(base.x[b]-focusX)?i:b,0);values.unshift(d.categories?.[k]??`${fmt(base.x[k])}`);}ui.read.textContent=values.join(' / ');}
 svg.addEventListener('pointermove',e=>{const b=svg.getBoundingClientRect(),x=(e.clientX-b.left)*size.w/b.width,y=(e.clientY-b.top)*size.h/b.height;inspect(scales.xmin+(x-size.L)/(size.w-size.L-size.R)*(scales.xmax-scales.xmin),y);});svg.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const step=d.kind==='bar'?(d.binWidth||1):(scales.xmax-scales.xmin)/100;inspect(e.key==='Home'?scales.xmin:e.key==='End'?scales.xmax:(focusX??0)+(e.key==='ArrowLeft'?-1:1)*step);});observeChartSize(host,draw,signal);draw();
}
function polarChart(host,d,signal){const ui=shell(host,d.title);d.patterns.forEach(p=>swatch(p.name,p.color,ui.legend));const svg=el('svg',{role:'img','aria-label':'Vertical radiation cut, modeled gain in dBi. Arrow keys change elevation and side.',tabindex:0});ui.stage.append(svg);const az=control(host,'Azimuth (°)',0,360,0,5);let current=0,side=1,geometry;
 function draw(){const w=host.clientWidth-32,h=330,r=Math.min(145,(w-70)/2),cx=w/2,cy=168;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('width',w);svg.setAttribute('height',h);svg.replaceChildren();const scale=g=>r*(clamp(g,-25,5)+25)/30;for(const g of [-20,-10,0,5]){svg.append(el('circle',{cx,cy,r:scale(g),fill:'none',class:'grid-line'}),el('text',{x:cx+5,y:cy-scale(g)-4,class:'tick'},`${g} dBi`));}svg.append(el('line',{x1:cx-r,y1:cy,x2:cx+r,y2:cy,class:'grid-line'}),el('line',{x1:cx,y1:cy-r,x2:cx,y2:cy+r,class:'grid-line'}));svg.append(el('text',{x:cx,y:cy-r-15,'text-anchor':'middle',class:'tick'},'Up'),el('text',{x:cx,y:cy+r+20,'text-anchor':'middle',class:'tick'},'Down'),el('text',{x:cx+r+5,y:cy+4,class:'tick'},'0°'));
 geometry={w,h,r,cx,cy,scale};const plane=Math.round(+az.value/5)%72;for(const p of d.patterns){const path=[];for(let j=0;j<=360;j++){
 const right=j<=180,elev=right?90-j:j-270;const idx=Math.round(elev+90);const gain=p.gain[(plane+(right?0:36))%72][clamp(idx,0,180)];const angle=j*Math.PI/180;const rr=scale(gain);path.push(`${j?'L':'M'}${cx+rr*Math.sin(angle)},${cy-rr*Math.cos(angle)}`);}svg.append(el('path',{d:path.join(' ')+'Z',fill:'none',stroke:colors[p.color],'stroke-width':2.4}));}read(current);}
 function read(e){current=clamp(Math.round(e),-90,90);const a=(Math.round(+az.value/5)+(side<0?36:0))%72;ui.read.textContent=`${current}° elevation / ${a*5}° azimuth / `+d.patterns.map(p=>`${p.name}: ${fmt(p.gain[a][current+90],2)} dBi`).join(' / ');svg.querySelector('.chart-cursor')?.remove();const cursor=el('g',{class:'chart-cursor','pointer-events':'none'}),{cx,cy,r,scale}=geometry,angle=current*Math.PI/180;cursor.append(el('line',{x1:cx,y1:cy,x2:cx+side*r*Math.cos(angle),y2:cy-r*Math.sin(angle),stroke:'#46444144','stroke-dasharray':'3 4'}));for(const p of d.patterns){const radius=scale(p.gain[a][current+90]);cursor.append(el('circle',{cx:cx+side*radius*Math.cos(angle),cy:cy-radius*Math.sin(angle),r:4,fill:colors[p.color],stroke:'#faf9f5','stroke-width':2}));}svg.append(cursor);}
 svg.addEventListener('pointermove',e=>{const b=svg.getBoundingClientRect(),x=(e.clientX-b.left)*geometry.w/b.width-geometry.cx,y=geometry.cy-(e.clientY-b.top)*geometry.h/b.height;side=x<0?-1:1;read(Math.atan2(y,Math.abs(x))*180/Math.PI);});svg.addEventListener('keydown',e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();if(e.key==='ArrowLeft')side=-1;if(e.key==='ArrowRight')side=1;read(current+(e.key==='ArrowUp'?1:e.key==='ArrowDown'?-1:0));});az.oninput=draw;observeChartSize(host,draw,signal);draw();}
function chirpChart(host,signal){const ui=shell(host,'LoRa symbol duration');const sf=control(host,'Spreading factor',7,12,9),bw=control(host,'Bandwidth (kHz)',0,2,0,1);const svg=el('svg',{role:'img','aria-label':'Ideal linear frequency sweeps at the selected LoRa settings'});ui.stage.append(svg);function draw(){const w=host.clientWidth-32,h=250,L=44,R=12,T=22,B=42,bandwidth=[125,250,500][+bw.value],duration=2**(+sf.value)/bandwidth,window=32.768;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('width',w);svg.setAttribute('height',h);svg.replaceChildren();for(let k=0;k<5;k++){const y=T+(h-T-B)*k/4;svg.append(el('line',{x1:L,x2:w-R,y1:y,y2:y,class:'grid-line'}),el('text',{x:L-7,y:y+4,'text-anchor':'end',class:'tick'},fmt(bandwidth/2-k*bandwidth/4,0)));}for(let t=0,k=0;t<window;t+=duration,k++){const end=Math.min(t+duration,window),x1=L+t/window*(w-L-R),x2=L+end/window*(w-L-R),y2=h-B-(end-t)/duration*(h-B-T);svg.append(el('line',{x1,x2,y1:h-B,y2,stroke:colors[k%7],'stroke-width':2}));}svg.append(el('text',{x:L,y:13,class:'axis-label'},'Frequency offset (kHz)'),el('text',{x:L,y:h-18,class:'tick'},'0'),el('text',{x:w-R,y:h-18,'text-anchor':'end',class:'tick'},`${window} ms`));ui.read.textContent=`SF${sf.value} / ${fmt(duration,3)} ms per symbol / ${2**(+sf.value)} chips per symbol`;}sf.oninput=draw;bw.oninput=()=>{bw.previousElementSibling.textContent=[125,250,500][+bw.value];draw();};bw.previousElementSibling.textContent=125;observeChartSize(host,draw,signal);draw();}
export function heatColor(t){const stops=[[56,34,98],[72,73,175],[43,144,194],[51,177,129],[184,203,66],[242,163,52],[211,58,77]];const v=clamp(t,0,1)*6,i=Math.min(5,Math.floor(v)),f=v-i;return stops[i].map((x,j)=>Math.round(x+(stops[i+1][j]-x)*f));}
async function waterfall(host,signal){const [m,b]=await Promise.all([fetch('/assets/payload-dev-log/waterfall.json').then(r=>r.json()),fetch('/assets/payload-dev-log/waterfall.bin').then(r=>r.arrayBuffer())]);if(signal.aborted)return;const values=new Float32Array(b),ui=shell(host,'June 3 radio capture');const canvas=document.createElement('canvas');canvas.width=m.cols;canvas.height=m.rows;canvas.className='waterfall-canvas';canvas.tabIndex=0;canvas.setAttribute('role','img');canvas.setAttribute('aria-label','Radio waterfall with time increasing downward, frequency increasing rightward');const axis=document.createElement('div');axis.className='waterfall-axis';axis.innerHTML=`<span>${fmt(m.startMHz,2)} MHz</span><span>${fmt(m.endMHz,2)} MHz</span>`;ui.stage.append(canvas,axis);const ctx=canvas.getContext('2d'),img=ctx.createImageData(m.cols,m.rows);for(let i=0;i<values.length;i++){const col=heatColor((values[i]-m.low)/(m.high-m.low));img.data.set([...col,255],i*4);}ctx.putImageData(img,0,0);ui.legend.innerHTML='<span>Time ↓</span><span class="spectrum-key"></span><span>Relative power, low to high</span>';let row=0,col=0;function show(){ui.read.textContent=`${fmt(row/m.rows*m.seconds)} s / ${fmt(m.startMHz+col/m.cols*(m.endMHz-m.startMHz),3)} MHz / ${fmt(values[row*m.cols+col])} dB (relative)`;}canvas.onpointermove=e=>{const b=canvas.getBoundingClientRect();col=clamp(Math.floor((e.clientX-b.left)/b.width*m.cols),0,m.cols-1);row=clamp(Math.floor((e.clientY-b.top)/b.height*m.rows),0,m.rows-1);show();};canvas.onkeydown=e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();row=clamp(row+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0),0,m.rows-1);col=clamp(col+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0),0,m.cols-1);show();};show();}
export function observeChartSize(host, draw, signal) {
 let width;
 const observer=new ResizeObserver(()=>{
  if(signal.aborted || !host.isConnected || host.clientWidth === width)return;
  width=host.clientWidth;
  draw();
 });
 observer.observe(host);
 signal.addEventListener('abort',()=>observer.disconnect(),{once:true});
}
export function mountCharts(root,signal) {
 const observer=new IntersectionObserver(entries=>{for(const e of entries){
  if(!e.isIntersecting || signal.aborted)continue;
  observer.unobserve(e.target);
  const host=e.target,key=host.dataset.chart;
  Promise.resolve().then(async()=>{
   if(key==='antenna-pattern'){
    const [{radiation},d]=await Promise.all([import('./radio-figures.js'),data()]);
    if(!signal.aborted)radiation(host,d['antenna-panels'],signal);
   }else if(key==='captured-chirps'){
    const {capturedChirps}=await import('./radio-figures.js');
    if(!signal.aborted)await capturedChirps(host,signal);
   }else if(key==='contact-wait'){
    const {contactFigure}=await import('./contact-figure.js');
    if(!signal.aborted)await contactFigure(host,signal);
   }else if(key==='chirps')chirpChart(host,signal);
   else if(key==='waterfall')await waterfall(host,signal);
   else if(key==='fleet'){
    const {fleet}=await import('./fleet.js');
    if(!signal.aborted)await fleet(host,signal);
   }else{
    const d=(await data())[key];
    if(signal.aborted)return;
    if(d.kind==='polar')polarChart(host,d,signal);else xyChart(host,d,signal);
   }
  }).catch(()=>{if(!signal.aborted)host.textContent='Figure could not load. Reload to try again.';});
 }},{rootMargin:'450px'});
 root.querySelectorAll('[data-chart]').forEach(h=>observer.observe(h));
 signal.addEventListener('abort',()=>observer.disconnect(),{once:true});
}
