import {colors,heatColor,observeChartSize} from './charts.js';
import {loadFleet} from './fleet-data.js';
const rad=Math.PI/180,R=6371,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export async function fleet(host,signal){
 const {meta,tracks:fleets,coast,wind}=await loadFleet();if(signal.aborted)return;let tracks=fleets.north;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 host.innerHTML='<div class="chart-heading">Wind-driven fleet <span>300 hPa</span></div><label class="fleet-distribution">Starting positions<select aria-label="Fleet starting positions"><option value="north">Northern hemisphere</option><option value="south">Southern hemisphere</option><option value="world">Both hemispheres</option></select></label><div class="fleet-metrics"><span><b data-north>…</b> of the northern hemisphere</span><span><b data-south>…</b> of the southern hemisphere</span><span><b data-global>…</b> of Earth</span></div><canvas class="fleet-map" tabindex="0" role="img" aria-label="Simulated balloons following historical NOAA wind, with coverage footprints"></canvas><div class="fleet-date"></div><div class="fleet-controls"><label>Balloon count <output>30</output><input type="range" min="1" max="500" value="30" aria-label="Balloon count"></label><label>Radius <output>350 km</output><input type="range" min="200" max="500" step="25" value="350" aria-label="Coverage radius in kilometers"></label><label class="fleet-time">Day <output>0</output><input type="range" min="0" max="336" value="0" step="0.1" aria-label="Simulation hour"></label></div><output class="chart-readout">NOAA winds, May 17–31, 2024</output>';
 const canvas=host.querySelector('canvas'),ctx=canvas.getContext('2d'),date=host.querySelector('.fleet-date'),read=host.querySelector('.chart-readout'),inputs=[...host.querySelectorAll('input')];const[countInput,radiusInput,timeInput]=inputs;
 let width=0,height=0,hour=0,n=30,radius=350,playing=!reduced.matches,visible=false,last=0,raf=0,metricKey='',selected=-1,positions=[];
 const worker=new Worker('/payload-dev-log/coverage-worker.js');let calculation=0;worker.onmessage=e=>{if(e.data.id!==calculation)return;host.querySelector('[data-north]').textContent=e.data.north.toFixed(1)+'%';host.querySelector('[data-south]').textContent=e.data.south.toFixed(1)+'%';host.querySelector('[data-global]').textContent=e.data.global.toFixed(1)+'%';host.querySelector('.fleet-metrics').title=`Instantaneous geometric area at hour ${e.data.hour}. Estimated from 6,000 equal-area points; no radio or power model.`;};
 host.querySelector('select').onchange=()=>{tracks=fleets[host.querySelector('select').value];metricKey='';selected=-1;draw();};
 function at(k,h){const a=Math.floor(h),b=Math.min(meta.steps,a+1),t=h-a,ia=(k*(meta.steps+1)+a)*2,ib=(k*(meta.steps+1)+b)*2;let dl=((tracks[ib+1]-tracks[ia+1]+540)%360)-180;return[tracks[ia]+(tracks[ib]-tracks[ia])*t,((tracks[ia+1]+dl*t+540)%360)-180];}
 function project(lat,lon){return[(lon+180)/360*width,(90-lat)/180*height];}
 function line(coords,color,alpha=1){ctx.beginPath();let px;for(const[lon,lat]of coords){const[x,y]=project(lat,lon);if(px===undefined||Math.abs(x-px)>width/2)ctx.moveTo(x,y);else ctx.lineTo(x,y);px=x;}ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.stroke();ctx.globalAlpha=1;}
 function ring(lat,lon,color){const a=radius/R,lt=lat*rad,ln=lon*rad;let pts=[];for(let i=0;i<=40;i++){const b=i*Math.PI/20,la=Math.asin(Math.sin(lt)*Math.cos(a)+Math.cos(lt)*Math.sin(a)*Math.cos(b)),lo=ln+Math.atan2(Math.sin(b)*Math.sin(a)*Math.cos(lt),Math.cos(a)-Math.sin(lt)*Math.sin(la));pts.push([((lo/rad+540)%360)-180,la/rad]);}line(pts,color,.35);}
 function draw(){if(!width)return;ctx.clearRect(0,0,width,height);ctx.fillStyle='#eeeee9';ctx.fillRect(0,0,width,height);ctx.lineWidth=.6;for(let lat=-60;lat<=60;lat+=30)line([[-180,lat],[0,lat],[180,lat]],'#d7d8d1');for(let lon=-150;lon<=150;lon+=30)line([[lon,-90],[lon,90]],'#d7d8d1');coast.forEach(c=>line(c,'#959c93',.8));
 const winds=wind[Math.min(56,Math.round(hour/6))];for(const[lat,lon,u,v]of winds){const[x,y]=project(lat,lon),speed=Math.hypot(u,v),len=clamp(speed/4,1,8);ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(-v,u));ctx.strokeStyle=`rgb(${heatColor(speed/65).join(',')})`;ctx.globalAlpha=.36;ctx.beginPath();ctx.moveTo(-len/2,0);ctx.lineTo(len/2,0);ctx.lineTo(len/2-2,-1.8);ctx.moveTo(len/2,0);ctx.lineTo(len/2-2,1.8);ctx.stroke();ctx.restore();}
 positions=[];for(let k=0;k<n;k++){const[lat,lon]=at(k,hour),color=colors[k%7];ring(lat,lon,color);if(k===selected||n<=60){const tail=[];for(let h=Math.max(0,hour-24);h<=hour;h+=2){const[lt,ln]=at(k,h);tail.push([ln,lt]);}line(tail,color,k===selected?1:.45);}const[x,y]=project(lat,lon);positions.push({x,y,k,lat,lon});ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,k===selected?4:2,0,Math.PI*2);ctx.fill();}
 timeInput.value=hour;timeInput.previousElementSibling.textContent=(hour/24).toFixed(1);date.textContent=new Date(Date.parse(meta.start)+hour*3600000).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'UTC'})+' UTC';
 const sampleHour=clamp(Math.round(hour),0,336),key=[host.querySelector('select').value,n,radius,sampleHour].join(':');if(key!==metricKey){metricKey=key;worker.postMessage({id:++calculation,hour:sampleHour,radius,positions:Array.from({length:n},(_,k)=>at(k,sampleHour))});}
 }
 function tick(t){raf=0;if(!playing||!visible||document.hidden)return;if(last)hour=(hour+Math.min(t-last,100)*.006)%336;last=t;draw();raf=requestAnimationFrame(tick);}
 function updatePlay(){last=0;if(playing&&visible&&!document.hidden&&!raf)raf=requestAnimationFrame(tick);if(!playing&&raf){cancelAnimationFrame(raf);raf=0;}}
 countInput.oninput=()=>{n=+countInput.value;countInput.previousElementSibling.textContent=n;selected=-1;draw();};radiusInput.oninput=()=>{radius=+radiusInput.value;radiusInput.previousElementSibling.textContent=radius+' km';draw();};timeInput.oninput=()=>{playing=false;hour=+timeInput.value;updatePlay();draw();};timeInput.onchange=()=>{playing=!reduced.matches;updatePlay();};
 canvas.onpointermove=e=>{const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)*width/b.width,y=(e.clientY-b.top)*height/b.height;const p=positions.reduce((a,p)=>Math.hypot(p.x-x,p.y-y)<Math.hypot(a.x-x,a.y-y)?p:a,positions[0]);selected=p&&Math.hypot(p.x-x,p.y-y)<22?p.k:-1;if(selected>=0)read.textContent=`Balloon ${p.k+1} / ${Math.abs(p.lat).toFixed(1)}°${p.lat>=0?'N':'S'} / ${Math.abs(p.lon).toFixed(1)}°${p.lon>=0?'E':'W'}`;draw();};canvas.onpointerleave=()=>{selected=-1;read.textContent='NOAA winds, May 17–31, 2024';draw();};canvas.onkeydown=e=>{if(e.key===' '){e.preventDefault();playing=!playing;updatePlay();return;}if(['ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();playing=false;hour=clamp(hour+(e.key==='ArrowRight'?6:-6),0,336);updatePlay();draw();}};
 observeChartSize(host,()=>{width=host.clientWidth-32;height=width/2;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);draw();},signal);
 const visibilityObserver=new IntersectionObserver(es=>{visible=es[0].isIntersecting;if(!visible&&raf){cancelAnimationFrame(raf);raf=0;}updatePlay();},{threshold:.1});visibilityObserver.observe(host);document.addEventListener('visibilitychange',updatePlay,{signal});reduced.addEventListener('change',()=>{if(reduced.matches){playing=false;updatePlay();}},{signal});window.addEventListener('pagehide',event=>{if(!event.persisted)worker.terminate();cancelAnimationFrame(raf);raf=0;},{signal});window.addEventListener('pageshow',updatePlay,{signal});signal.addEventListener('abort',()=>{worker.terminate();cancelAnimationFrame(raf);visibilityObserver.disconnect();},{once:true});updatePlay();
}
