[env:stratolink]
platform = ststm32
board = stratolink
framework = arduino
boards_dir = boards
build_type = debug

monitor_speed = 115200
upload_protocol = jlink
debug_tool = custom
debug_server =
    JLinkGDBServerCL
    -device
    STM32WLE5CC
    -if
    SWD
    -speed
    4000

lib_deps =
    sparkfun/SparkFun u-blox GNSS v3@^3.1.7
    stm32duino/STM32duino Low Power@^1.2.0
    jgromes/RadioLib@^7.6.0
build_unflags = -DCUSTOM_PERIPHERAL_PINS

build_flags =
    -D ARDUINO_ARCH_STM32
    -D ARDUINO_RAK3172_MODULE
    -D HAL_UART_MODULE_ENABLED
    -D HAL_TIM_MODULE_ONLY
    -D ENABLE_HWSERIAL1
    -D PIN_SERIAL1_TX=PB_6
    -D PIN_SERIAL1_RX=PB_7
    -D REGION_US915
    -I include
